ALTER TABLE "File" DROP CONSTRAINT IF EXISTS "File_projectId_fkey";
ALTER TABLE "File" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "File"
ADD CONSTRAINT "File_projectId_fkey"
FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
